### ISSUE TITLE
where is dto file?

### ISSUE THREAD

**Issue by Eurus-Holmes** [Flowingsun007/LyonBlog#2]
In the `com.flowingsun.article.entity`, the `Article.java` import: 
```java
import com.flowingsun.article.dto.ArticleTag;
import com.flowingsun.article.dto.RegularRecommend;
import com.flowingsun.behavior.dto.BehaviorStatus;
```

Where is dto?

**Comment by Flowingsun007** [comment]
Sorry,I've just fix it,pleace retry.There might be something wrong with 'master' branch,You can choose 'server' branch!
